Remove compile_task flag from documentation
google/ml-compiler-opt pull request #341
Opened 2024-04-03 08:17 UTC by boomanaiden154

This patch removes the compile_task flag from the evaluation documentation for the inliner demo. This flag was removed in 2ba448732b5c9aa9ed221ac70a0009293651701e and the documentation was never updated.

Fixes #340.

2024-04-03 16:34 UTC, TIHan approved these changes

2024-04-03 23:20 UTC, TIHan requested changes
There are actually a few issues with the command besides `--compile_task`.

This is exactly what I used to get it to run:
```bash
export OUTPUT_PERFORMANCE_PATH=$HOME/performance_report
PYTHONPATH=$PYTHONPATH:. python3 \
  compiler_opt/tools/generate_default_trace.py \
  --data_path=$CORPUS \
  --policy_path=$OUTPUT_DIR/saved_policy \
  --output_performance_path=$OUTPUT_PERFORMANCE_PATH \
  --gin_files=compiler_opt/rl/inlining/gin_configs/common.gin \
  --gin_bindings=clang_path="'$LLVM_INSTALLDIR/bin/clang'" \
  --gin_bindings=llvm_size_path="'$LLVM_INSTALLDIR/bin/llvm-size'" \
  --sampling_rate=0.2
```

There was a mistaken `"'=$LLVM..` that should have been `="'$LLVM..`.

There was also a weird thing with the `PYTHONPATH`:
Instead of:
```bash
PYTHONPATH=$PYTHONPATH:. && \
python3 compiler_opt/tools/generate_default_trace.py \
```
It needs to be:
```bash
PYTHONPATH=$PYTHONPATH:. python3 \
  compiler_opt/tools/generate_default_trace.py \
```

2024-04-04 07:07 UTC, boomanaiden154 commented
The other issues should be addressed now as well. Thanks for reporting them to improve the documentation!

2024-04-04 16:49 UTC, TIHan approved these changes

2024-04-09 02:48 UTC, merged